<?php

// File: /Applications/MAMP/htdocs/wordpress/wp-content/plugins/gpt3-ai-content-generator/classes/images/manager/ajax/ajax_delete_generated_image.php
// Status: NEW FILE

namespace WPAICG\Images\Manager\Ajax;

use WP_Error;

if (!defined('ABSPATH')) {
    exit;
}

function ajax_delete_generated_image_logic(): void
{
    check_ajax_referer('aipkit_image_generator_nonce', '_ajax_nonce');
    if (!is_user_logged_in()) {
        wp_send_json_error(['message' => __('You must be logged in to delete images.', 'gpt3-ai-content-generator')], 403);
        return;
    }
    $attachment_id = isset($_POST['attachment_id']) ? absint($_POST['attachment_id']) : 0;
    if (empty($attachment_id)) {
        wp_send_json_error(['message' => __('Invalid image ID.', 'gpt3-ai-content-generator')], 400);
        return;
    }

    $post_author_id = get_post_field('post_author', $attachment_id);
    if (get_current_user_id() != $post_author_id) {
        if (!current_user_can('manage_options')) {
            wp_send_json_error(['message' => __('You do not have permission to delete this image.', 'gpt3-ai-content-generator')], 403);
            return;
        }
    }

    $is_aipkit_image = get_post_meta($attachment_id, '_aipkit_generated_image', true);
    if ($is_aipkit_image !== '1') {
        wp_send_json_error(['message' => __('This image was not generated by AI Power.', 'gpt3-ai-content-generator')], 403);
        return;
    }

    $deleted = wp_delete_attachment($attachment_id, true);

    if ($deleted === false) {
        wp_send_json_error(['message' => __('Failed to delete the image from the media library.', 'gpt3-ai-content-generator')], 500);
    } else {
        wp_send_json_success(['message' => __('Image deleted successfully.', 'gpt3-ai-content-generator')]);
    }
}
